### ISSUE TITLE
Bug: Creating Node.js block with node js sample repo populates repository with C# dockerfile

### ISSUE THREAD

**Issue by denistsoi** [kintohub/backlog#24]
**Expected Behavior**
Populating block should have node js sample 

**Current Behavior**
Dockerfile contains dot.net references (see below)

**How to Reproduce**
1. Create new KintoBlock 
2. Select Node.js as language
3. Select "Create new Kintoblock" button
4. View linked repository dockerfile.

<img width="1680" alt="screen shot 2018-07-12 at 5 03 55 pm" src="https://user-images.githubusercontent.com/3061779/42623527-ad4e37da-85f5-11e8-9cbf-a257fe607734.png">

<img width="1680" alt="screen shot 2018-07-12 at 5 04 18 pm" src="https://user-images.githubusercontent.com/3061779/42623524-ac22094a-85f5-11e8-9828-eaa7bb94e7cc.png">

**Comment by Disturbing** [comment]
➤ Joseph Cooper commented:

Release 0.1.4 Today, will provide release notes soon, but this issue has been resolved.

Thanks for the report!
