### ISSUE TITLE
[Docs] Broken link in documentation

### ISSUE THREAD

**Issue by vishal-biyani** [kintohub/backlog#35]
There are two broken links in https://docs.kintohub.com/docs/getting-started guide: creating-a-kintoblock.md and tagging-a-commit.md are broken

┆Status: Committed
┆Category: Bug
┆PrioRating: Very High
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;get_asset?asset_id&#x3D;802191458027306">Screen Shot 2018-08-31 at 9.40.45 AM.png</a>

**Comment by denistsoi** [comment]
for maintainers of docs
```
https://docs.kintohub.com/docs/getting-started#tag-latest-commit
```
``` md
### Tag Latest Commit

_For more details and screenshots about tagging latest commit read more [here](tagging-a-commit.md)_
```

``` link
https://docs.kintohub.com/docs/getting-started#create-a-kintoblock-on-kintohub-from-the-service-we-just-created
```
``` md
## Create a Kintoblock on KintoHub from the service we just created

_For more details and screenshots about creating KintoBlocks read more [here](creating-a-kintoblock.md)_
```

**Comment by Disturbing** [comment]
➤ Laura Ambrose commented:

[Joseph Cooper](https://app.asana.com/0/303069452188272/list) PR is ready 🙂

**Comment by Disturbing** [comment]
➤ Seema commented:

Please see the attached link. This is broken

**Comment by Disturbing** [comment]
➤ Laura Ambrose commented:

https://github.com/kintohub/kintohub-docs/pull/34
The PR has not been accepted yet 😢
